---
project_name: mchfuse

release:
  github:
    owner: mnencia
    name: mchfuse

before:
  hooks:
    - go mod download

builds:
- binary: mchfuse
  ldflags: -s -w -X main.revision={{.ShortCommit}} -X main.revisionDate={{.CommitDate}} -X main.version={{.Version}}
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  - arm
  - 386
  - ppc64le
  - s390x
  - mips64
  - mips64le
  goarm:
  - 5
  - 6
  - 7
  env:
  - CGO_ENABLED=0
  ignore:
  - goos: darwin
    goarch: 386

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  skip: true

signs:
  - artifacts: checksum
